<a href="https://www.kaggle.com/code/ahmedfakhar123/ml-lab-02-working-with-csv-files-using-pandas?scriptVersionId=339064547" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

---
# 💻 ML Lab 02 — Working with CSV Files Using Pandas

### *Learn how to load, explore, and manipulate real-world datasets for Machine Learning*

---


> **Before building Machine Learning models, you must know how to work with datasets.**
>
> In this lab, you'll learn how to import CSV files, inspect datasets, and perform the essential data manipulation tasks that every Machine Learning Engineer uses daily.

---

# 🎯 What You'll Learn

By the end of this notebook, you'll be able to:

- 📥 Import CSV datasets using Pandas
- 📊 Explore dataset structure
- 🔍 Inspect rows and columns
- 📋 View dataset information
- 📈 Generate descriptive statistics
- ❓ Detect missing values
- 🔁 Identify duplicate records
- 🎯 Select rows and columns
- 🔎 Filter data
- ➕ Create new columns
- 💾 Save processed datasets

---

# 📦 Dataset

We'll use the **Student Placement Prediction** dataset throughout this notebook.

It contains academic information about students along with their placement status, making it perfect for learning how to work with tabular data before training Machine Learning models.

---
# 1️⃣ Importing Libraries

- NumPy
- Pandas

In [1]:
# Data manipulation
import numpy as np
import pandas as pd

---

# 2️⃣ Loading CSV Files

- `pd.read_csv()`
- Reading datasets from Kaggle

In [2]:
df = pd.read_csv("/kaggle/input/datasets/biplavkant/placement/placement.csv")
df

     cgpa  placement_exam_marks  placed
0    7.19                  26.0       1
1    7.46                  38.0       1
2    7.54                  40.0       1
3    6.42                   8.0       1
4    7.23                  17.0       0
..    ...                   ...     ...
995  8.87                  44.0       1
996  9.12                  65.0       1
997  4.89                  34.0       0
998  8.62                  46.0       1
999  4.90                  10.0       1

[1000 rows x 3 columns]

---

# 3️⃣ Exploring the Dataset

- `head()`
- `tail()`
- `sample()`
- `shape`
- `columns`
- `index`

In [3]:
df.head()

   cgpa  placement_exam_marks  placed
0  7.19                  26.0       1
1  7.46                  38.0       1
2  7.54                  40.0       1
3  6.42                   8.0       1
4  7.23                  17.0       0

In [4]:
df.tail()

     cgpa  placement_exam_marks  placed
995  8.87                  44.0       1
996  9.12                  65.0       1
997  4.89                  34.0       0
998  8.62                  46.0       1
999  4.90                  10.0       1

In [5]:
df.shape

(1000, 3)

In [6]:
df.columns

Index(['cgpa', 'placement_exam_marks', 'placed'], dtype='object')

---

# 4️⃣ Understanding the Dataset

- `info()`
- `describe()`
- `dtypes`

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cgpa                  1000 non-null   float64
 1   placement_exam_marks  1000 non-null   float64
 2   placed                1000 non-null   int64
dtypes: float64(2), int64(1)
memory usage: 23.6 KB

In [8]:
df.describe()

              cgpa  placement_exam_marks       placed
count  1000.000000           1000.000000  1000.000000
mean      6.961240             32.225000     0.489000
std       0.615898             19.130822     0.500129
min       4.890000              0.000000     0.000000
25%       6.550000             17.000000     0.000000
50%       6.960000             28.000000     0.000000
75%       7.370000             44.000000     1.000000
max       9.120000            100.000000     1.000000

In [9]:
df.dtypes

cgpa                    float64
placement_exam_marks    float64
placed                    int64
dtype: object

# 5️⃣ Selecting Data

Selecting specific rows and columns is one of the most common tasks when working with datasets. Pandas provides several ways to access data efficiently.

## 5.1 Selecting a Single Column

In [10]:
df["cgpa"]

0      7.19
1      7.46
2      7.54
3      6.42
4      7.23
       ...
995    8.87
996    9.12
997    4.89
998    8.62
999    4.90
Name: cgpa, Length: 1000, dtype: float64


## 5.2 Selecting Multiple Columns

In [11]:
df[["cgpa", "placement_exam_marks"]]

     cgpa  placement_exam_marks
0    7.19                  26.0
1    7.46                  38.0
2    7.54                  40.0
3    6.42                   8.0
4    7.23                  17.0
..    ...                   ...
995  8.87                  44.0
996  9.12                  65.0
997  4.89                  34.0
998  8.62                  46.0
999  4.90                  10.0

[1000 rows x 2 columns]


## 5.3 Selecting Rows using `loc`

Select rows by their labels.

In [12]:
df.loc[0]

cgpa                     7.19
placement_exam_marks    26.00
placed                   1.00
Name: 0, dtype: float64

In [13]:
df.loc[0:4]

   cgpa  placement_exam_marks  placed
0  7.19                  26.0       1
1  7.46                  38.0       1
2  7.54                  40.0       1
3  6.42                   8.0       1
4  7.23                  17.0       0

In [14]:
df.loc[:, ["cgpa", "placed"]]

     cgpa  placed
0    7.19       1
1    7.46       1
2    7.54       1
3    6.42       1
4    7.23       0
..    ...     ...
995  8.87       1
996  9.12       1
997  4.89       0
998  8.62       1
999  4.90       1

[1000 rows x 2 columns]

## 5.4 Selecting Rows using `iloc`

Select rows by their integer positions.

In [15]:
df.iloc[0]

cgpa                     7.19
placement_exam_marks    26.00
placed                   1.00
Name: 0, dtype: float64

In [16]:
df.iloc[0:5]

   cgpa  placement_exam_marks  placed
0  7.19                  26.0       1
1  7.46                  38.0       1
2  7.54                  40.0       1
3  6.42                   8.0       1
4  7.23                  17.0       0

In [17]:
df.iloc[:, 0:2]

     cgpa  placement_exam_marks
0    7.19                  26.0
1    7.46                  38.0
2    7.54                  40.0
3    6.42                   8.0
4    7.23                  17.0
..    ...                   ...
995  8.87                  44.0
996  9.12                  65.0
997  4.89                  34.0
998  8.62                  46.0
999  4.90                  10.0

[1000 rows x 2 columns]

---

# 6️⃣ Filtering Data

Filtering allows us to retrieve only the records that satisfy specific conditions.

## 6.1 Conditional Filtering

Students with CGPA greater than 8.

In [18]:
df[df["cgpa"] > 8]

     cgpa  placement_exam_marks  placed
34   8.15                   9.0       0
37   8.51                   9.0       1
49   8.23                  28.0       1
54   8.42                  36.0       1
55   8.12                  15.0       0
67   8.04                  18.0       1
76   8.35                  12.0       0
78   8.20                  12.0       0
98   8.12                  76.0       0
131  8.19                  19.0       1
139  8.09                   5.0       1
150  8.53                  22.0       0
194  8.19                  33.0       0
198  8.29                  44.0       1
234  8.09                  36.0       0
263  8.11                  50.0       1
275  8.03                  39.0       0
279  8.49                  40.0       1
290  8.38                  87.0       0
327  8.21                  56.0       0
349  8.12                  16.0       0
404  8.02                  35.0       1
407  8.23                  20.0       1
423  8.27                  26.0       0
440  8.56                  22.0       0
492  8.50                  21.0       1
568  8.13                   4.0       0
596  8.48                  25.0       1
614  8.05                  41.0       0
629  8.15                  11.0       1
684  8.02                  67.0       0
689  8.02                  67.0       0
761  8.02                   6.0       0
773  8.06                  79.0       0
797  8.14                  20.0       1
811  8.04                  14.0       0
850  8.39                  37.0       1
863  8.04                   2.0       1
867  8.04                  26.0       0
935  8.12                  37.0       1
964  8.09                  54.0       1
975  8.43                  25.0       1
981  8.06                  37.0       0
995  8.87                  44.0       1
996  9.12                  65.0       1
998  8.62                  46.0       1

## 6.2 Multiple Conditions

Students with CGPA greater than 7 and placed.

In [19]:
df[(df["cgpa"] > 7) & (df["placed"] == 1)]

     cgpa  placement_exam_marks  placed
0    7.19                  26.0       1
1    7.46                  38.0       1
2    7.54                  40.0       1
5    7.30                  23.0       1
7    7.12                  39.0       1
..    ...                   ...     ...
975  8.43                  25.0       1
986  7.09                  19.0       1
995  8.87                  44.0       1
996  9.12                  65.0       1
998  8.62                  46.0       1

[238 rows x 3 columns]


Students with CGPA greater than 8 or placed.

In [20]:
df[(df["cgpa"] > 8) | (df["placed"] == 1)]

     cgpa  placement_exam_marks  placed
0    7.19                  26.0       1
1    7.46                  38.0       1
2    7.54                  40.0       1
3    6.42                   8.0       1
5    7.30                  23.0       1
..    ...                   ...     ...
993  6.73                  21.0       1
995  8.87                  44.0       1
996  9.12                  65.0       1
998  8.62                  46.0       1
999  4.90                  10.0       1

[512 rows x 3 columns]



## 6.3 Boolean Indexing

Store the condition in a Boolean variable.

In [21]:
high_cgpa = df["cgpa"] > 8

df[high_cgpa]

     cgpa  placement_exam_marks  placed
34   8.15                   9.0       0
37   8.51                   9.0       1
49   8.23                  28.0       1
54   8.42                  36.0       1
55   8.12                  15.0       0
67   8.04                  18.0       1
76   8.35                  12.0       0
78   8.20                  12.0       0
98   8.12                  76.0       0
131  8.19                  19.0       1
139  8.09                   5.0       1
150  8.53                  22.0       0
194  8.19                  33.0       0
198  8.29                  44.0       1
234  8.09                  36.0       0
263  8.11                  50.0       1
275  8.03                  39.0       0
279  8.49                  40.0       1
290  8.38                  87.0       0
327  8.21                  56.0       0
349  8.12                  16.0       0
404  8.02                  35.0       1
407  8.23                  20.0       1
423  8.27                  26.0       0
440  8.56                  22.0       0
492  8.50                  21.0       1
568  8.13                   4.0       0
596  8.48                  25.0       1
614  8.05                  41.0       0
629  8.15                  11.0       1
684  8.02                  67.0       0
689  8.02                  67.0       0
761  8.02                   6.0       0
773  8.06                  79.0       0
797  8.14                  20.0       1
811  8.04                  14.0       0
850  8.39                  37.0       1
863  8.04                   2.0       1
867  8.04                  26.0       0
935  8.12                  37.0       1
964  8.09                  54.0       1
975  8.43                  25.0       1
981  8.06                  37.0       0
995  8.87                  44.0       1
996  9.12                  65.0       1
998  8.62                  46.0       1

---

# 7️⃣ Missing Values

Missing values are common in real-world datasets. Pandas makes it easy to detect them.

## 7.1 Check Missing Values

In [22]:
df.isnull()

      cgpa  placement_exam_marks  placed
0    False                 False   False
1    False                 False   False
2    False                 False   False
3    False                 False   False
4    False                 False   False
..     ...                   ...     ...
995  False                 False   False
996  False                 False   False
997  False                 False   False
998  False                 False   False
999  False                 False   False

[1000 rows x 3 columns]

## 7.2 Count Missing Values

In [23]:
df.isnull().sum()

cgpa                    0
placement_exam_marks    0
placed                  0
dtype: int64

---

# 8️⃣ Duplicate Values

Duplicate records can negatively affect Machine Learning models, so they should be identified and removed.

## 8.1 Check Duplicate Rows

In [24]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

## 8.2 Count Duplicate Rows

In [25]:
df.duplicated().sum()

np.int64(19)

## 8.3 Remove Duplicate Rows

In [26]:
df.drop_duplicates(inplace=True)

---

# 9️⃣ Saving the Dataset

After cleaning or modifying the dataset, we can save it as a new CSV file.

In [27]:
df.to_csv("cleaned_dataset.csv", index=False)

The file **`cleaned_dataset.csv`** will be saved in the current working directory and can be downloaded or used in future Machine Learning projects.

---

# 🎯 Conclusion

Congratulations! 🎉

After completing this lab, you can now:

- 📥 Load CSV datasets using Pandas
- 📊 Explore and inspect datasets
- 🎯 Select specific rows and columns
- 🔎 Filter data using conditions
- ❓ Detect missing values
- 🔁 Identify and remove duplicate records
- ➕ Create and modify columns
- 💾 Save processed datasets

These are the core Pandas skills used in almost every Data Science and Machine Learning project. 🚀

---
# 🚀 What's Next?

[**💻 ML Lab 03 — Working with JSON & SQL Data Using Pandas**](http://https://www.kaggle.com/code/ahmedfakhar123/ml-lab-03-working-with-json-sql-data)

In this lab, you'll go beyond CSV files and learn how to work with other popular data formats used in real-world Machine Learning projects.

You'll learn:

- 📄 Reading JSON files with Pandas
- 🗄️ Connecting to SQL databases
- 📥 Loading data using SQL queries
- 🔄 Converting between DataFrames and different file formats
- ⚡ Working with structured data from multiple sources

By the end of this lab, you'll be able to import and analyze data from **CSV, JSON, and SQL**, giving you the essential data-handling skills required for Data Science and Machine Learning.

---

# ❤️ Support

If you found this notebook helpful:

- ⭐ Upvote this notebook
- 💬 Leave your feedback in the comments
- 🔁 Share it with fellow learners
- 🚀 Follow me for more beginner-friendly AI, Data Science, and Machine Learning content

Happy Learning! 🤖