<a href="https://www.kaggle.com/code/ahmedfakhar123/ml-lab-02-working-with-csv-files-using-pandas?scriptVersionId=339050779" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

---
# 💻 ML Lab 02 — Working with CSV Files Using Pandas

### *Learn how to load, explore, and manipulate real-world datasets for Machine Learning*

---


> **Before building Machine Learning models, you must know how to work with datasets.**
>
> In this lab, you'll learn how to import CSV files, inspect datasets, and perform the essential data manipulation tasks that every Machine Learning Engineer uses daily.

---

# 🎯 What You'll Learn

By the end of this notebook, you'll be able to:

- 📥 Import CSV datasets using Pandas
- 📊 Explore dataset structure
- 🔍 Inspect rows and columns
- 📋 View dataset information
- 📈 Generate descriptive statistics
- ❓ Detect missing values
- 🔁 Identify duplicate records
- 🎯 Select rows and columns
- 🔎 Filter data
- ➕ Create new columns
- 💾 Save processed datasets

---

# 📦 Dataset

We'll use the **Student Placement Prediction** dataset throughout this notebook.

It contains academic information about students along with their placement status, making it perfect for learning how to work with tabular data before training Machine Learning models.

---
# 1️⃣ Importing Libraries

- NumPy
- Pandas

In [2]:
# Data manipulation
import numpy as np
import pandas as pd

---

## 2️⃣ Loading CSV Files

- `pd.read_csv()`
- Reading datasets from Kaggle

In [4]:
df = pd.read_csv("/kaggle/input/datasets/biplavkant/placement/placement.csv")
df

     cgpa  placement_exam_marks  placed
0    7.19                  26.0       1
1    7.46                  38.0       1
2    7.54                  40.0       1
3    6.42                   8.0       1
4    7.23                  17.0       0
..    ...                   ...     ...
995  8.87                  44.0       1
996  9.12                  65.0       1
997  4.89                  34.0       0
998  8.62                  46.0       1
999  4.90                  10.0       1

[1000 rows x 3 columns]

---

## 3️⃣ Exploring the Dataset

- `head()`
- `tail()`
- `sample()`
- `shape`
- `columns`
- `index`

In [5]:
df.head()

   cgpa  placement_exam_marks  placed
0  7.19                  26.0       1
1  7.46                  38.0       1
2  7.54                  40.0       1
3  6.42                   8.0       1
4  7.23                  17.0       0

In [6]:
df.tail()

     cgpa  placement_exam_marks  placed
995  8.87                  44.0       1
996  9.12                  65.0       1
997  4.89                  34.0       0
998  8.62                  46.0       1
999  4.90                  10.0       1

In [7]:
df.shape

(1000, 3)

In [8]:
df.columns

Index(['cgpa', 'placement_exam_marks', 'placed'], dtype='object')

---

## 4️⃣ Understanding the Dataset

- `info()`
- `describe()`
- `dtypes`

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cgpa                  1000 non-null   float64
 1   placement_exam_marks  1000 non-null   float64
 2   placed                1000 non-null   int64
dtypes: float64(2), int64(1)
memory usage: 23.6 KB

In [10]:
df.describe()

              cgpa  placement_exam_marks       placed
count  1000.000000           1000.000000  1000.000000
mean      6.961240             32.225000     0.489000
std       0.615898             19.130822     0.500129
min       4.890000              0.000000     0.000000
25%       6.550000             17.000000     0.000000
50%       6.960000             28.000000     0.000000
75%       7.370000             44.000000     1.000000
max       9.120000            100.000000     1.000000

In [13]:
df.dtypes

cgpa                    float64
placement_exam_marks    float64
placed                    int64
dtype: object

---

## 5️⃣ Selecting Data

- Single column
- Multiple columns
- Rows using `loc`
- Rows using `iloc`

---

## 6️⃣ Filtering Data

- Conditional filtering
- Multiple conditions
- Boolean indexing

---

## 7️⃣ Missing Values

- `isnull()`
- `sum()`

---

## 8️⃣ Duplicate Values

- `duplicated()`
- `drop_duplicates()`

---

## 9️⃣ Creating New Columns

- Feature creation
- Column operations

---

## 🔟 Saving the Dataset

- `to_csv()`

---

# 🎯 Learning Outcome

After completing this lab, you'll be able to confidently work with CSV datasets using Pandas and prepare data for Machine Learning projects.

These skills form the foundation of every Data Scientist and Machine Learning Engineer's workflow.