<a href="https://www.kaggle.com/code/ahmedfakhar123/ml-lab-02-working-with-csv-files-using-pandas?scriptVersionId=339055708" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

---
# 💻 ML Lab 02 — Working with CSV Files Using Pandas

### *Learn how to load, explore, and manipulate real-world datasets for Machine Learning*

---


> **Before building Machine Learning models, you must know how to work with datasets.**
>
> In this lab, you'll learn how to import CSV files, inspect datasets, and perform the essential data manipulation tasks that every Machine Learning Engineer uses daily.

---

# 🎯 What You'll Learn

By the end of this notebook, you'll be able to:

- 📥 Import CSV datasets using Pandas
- 📊 Explore dataset structure
- 🔍 Inspect rows and columns
- 📋 View dataset information
- 📈 Generate descriptive statistics
- ❓ Detect missing values
- 🔁 Identify duplicate records
- 🎯 Select rows and columns
- 🔎 Filter data
- ➕ Create new columns
- 💾 Save processed datasets

---

# 📦 Dataset

We'll use the **Student Placement Prediction** dataset throughout this notebook.

It contains academic information about students along with their placement status, making it perfect for learning how to work with tabular data before training Machine Learning models.

---
# 1️⃣ Importing Libraries

- NumPy
- Pandas

In [1]:
# Data manipulation
import numpy as np
import pandas as pd

---

# 2️⃣ Loading CSV Files

- `pd.read_csv()`
- Reading datasets from Kaggle

In [2]:
df = pd.read_csv("/kaggle/input/datasets/biplavkant/placement/placement.csv")
df

     cgpa  placement_exam_marks  placed
0    7.19                  26.0       1
1    7.46                  38.0       1
2    7.54                  40.0       1
3    6.42                   8.0       1
4    7.23                  17.0       0
..    ...                   ...     ...
995  8.87                  44.0       1
996  9.12                  65.0       1
997  4.89                  34.0       0
998  8.62                  46.0       1
999  4.90                  10.0       1

[1000 rows x 3 columns]

---

# 3️⃣ Exploring the Dataset

- `head()`
- `tail()`
- `sample()`
- `shape`
- `columns`
- `index`

In [3]:
df.head()

   cgpa  placement_exam_marks  placed
0  7.19                  26.0       1
1  7.46                  38.0       1
2  7.54                  40.0       1
3  6.42                   8.0       1
4  7.23                  17.0       0

In [4]:
df.tail()

     cgpa  placement_exam_marks  placed
995  8.87                  44.0       1
996  9.12                  65.0       1
997  4.89                  34.0       0
998  8.62                  46.0       1
999  4.90                  10.0       1

In [5]:
df.shape

(1000, 3)

In [6]:
df.columns

Index(['cgpa', 'placement_exam_marks', 'placed'], dtype='object')

---

# 4️⃣ Understanding the Dataset

- `info()`
- `describe()`
- `dtypes`

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cgpa                  1000 non-null   float64
 1   placement_exam_marks  1000 non-null   float64
 2   placed                1000 non-null   int64
dtypes: float64(2), int64(1)
memory usage: 23.6 KB

In [8]:
df.describe()

              cgpa  placement_exam_marks       placed
count  1000.000000           1000.000000  1000.000000
mean      6.961240             32.225000     0.489000
std       0.615898             19.130822     0.500129
min       4.890000              0.000000     0.000000
25%       6.550000             17.000000     0.000000
50%       6.960000             28.000000     0.000000
75%       7.370000             44.000000     1.000000
max       9.120000            100.000000     1.000000

In [9]:
df.dtypes

cgpa                    float64
placement_exam_marks    float64
placed                    int64
dtype: object

# 5️⃣ Selecting Data

Selecting specific rows and columns is one of the most common tasks when working with datasets. Pandas provides several ways to access data efficiently.

## 5.1 Selecting a Single Column

```python
df["cgpa"]
```

## 5.2 Selecting Multiple Columns

```python
df[["cgpa", "placement_exam_marks"]]
```


## 5.3 Selecting Rows using `loc`

Select rows by their labels.

```python
df.loc[0]
```

```python
df.loc[0:4]
```

```python
df.loc[:, ["cgpa", "placed"]]
```


## 5.4 Selecting Rows using `iloc`

Select rows by their integer positions.

```python
df.iloc[0]
```

```python
df.iloc[0:5]
```

```python
df.iloc[:, 0:2]
```

---

# 6️⃣ Filtering Data

Filtering allows us to retrieve only the records that satisfy specific conditions.

## 6.1 Conditional Filtering

Students with CGPA greater than 8.

```python
df[df["cgpa"] > 8]
```


## 6.2 Multiple Conditions

Students with CGPA greater than 7 and placed.

```python
df[(df["cgpa"] > 7) & (df["placed"] == 1)]
```

Students with CGPA greater than 8 or placed.

```python
df[(df["cgpa"] > 8) | (df["placed"] == 1)]
```


## 6.3 Boolean Indexing

Store the condition in a Boolean variable.

```python
high_cgpa = df["cgpa"] > 8

df[high_cgpa]
```

---

# 7️⃣ Missing Values

Missing values are common in real-world datasets. Pandas makes it easy to detect them.

## 7.1 Check Missing Values

```python
df.isnull()
```


## 7.2 Count Missing Values

```python
df.isnull().sum()
```

---

# 8️⃣ Duplicate Values

Duplicate records can negatively affect Machine Learning models, so they should be identified and removed.

## 8.1 Check Duplicate Rows

```python
df.duplicated()
```



## 8.2 Count Duplicate Rows

```python
df.duplicated().sum()
```



## 8.3 Remove Duplicate Rows

```python
df.drop_duplicates(inplace=True)
```

---

# 9️⃣ Creating New Columns

Feature engineering often starts by creating new columns from existing data.

## 9.1 Create a New Column

```python
df["total_score"] = df["cgpa"] + df["placement_exam_marks"]

df.head()
```



## 9.2 Modify an Existing Column

Increase CGPA by 0.1 (for demonstration).

```python
df["cgpa"] = df["cgpa"] + 0.1

df.head()
```



## 9.3 Delete a Column

```python
df.drop(columns=["total_score"], inplace=True)
```

---

# 🔟 Saving the Dataset

After cleaning or modifying the dataset, we can save it as a new CSV file.

## 10.1 Save as CSV

```python
df.to_csv("cleaned_dataset.csv", index=False)
```

The file **`cleaned_dataset.csv`** will be saved in the current working directory and can be downloaded or used in future Machine Learning projects.

---

# 🎯 Conclusion

Congratulations! 🎉

After completing this lab, you can now:

- 📥 Load CSV datasets using Pandas
- 📊 Explore and inspect datasets
- 🎯 Select specific rows and columns
- 🔎 Filter data using conditions
- ❓ Detect missing values
- 🔁 Identify and remove duplicate records
- ➕ Create and modify columns
- 💾 Save processed datasets

These are the core Pandas skills used in almost every Data Science and Machine Learning project. 🚀

---
# 🚀 What's Next?

[**💻 ML Lab 03 — Working with JSON & SQL Data Using Pandas**](http://)

In this lab, you'll go beyond CSV files and learn how to work with other popular data formats used in real-world Machine Learning projects.

You'll learn:

- 📄 Reading JSON files with Pandas
- 🗄️ Connecting to SQL databases
- 📥 Loading data using SQL queries
- 🔄 Converting between DataFrames and different file formats
- ⚡ Working with structured data from multiple sources

By the end of this lab, you'll be able to import and analyze data from **CSV, JSON, and SQL**, giving you the essential data-handling skills required for Data Science and Machine Learning.

---

# ❤️ Support

If you found this notebook helpful:

- ⭐ Upvote this notebook
- 💬 Leave your feedback in the comments
- 🔁 Share it with fellow learners
- 🚀 Follow me for more beginner-friendly AI, Data Science, and Machine Learning content

Happy Learning! 🤖