<a href="https://www.kaggle.com/code/ahmedfakhar123/ml-lab-04-fetching-data-from-an-api?scriptVersionId=339264980" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

---

# 💻 ML Lab 04 — Fetching Data from an API

In [1]:
import pandas as pd
import requests

In [2]:
response = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1")

In [3]:
columns = [
    "id",
    "title",
    "original_title",
    "original_language",
    "genre_ids",
    "overview",
    "release_date",
    "popularity",
    "vote_average",
    "vote_count"
]

In [4]:
df = pd.DataFrame(response.json()["results"])[columns]
df.head()

,id,title,original_title,original_language,genre_ids,overview,release_date,popularity,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,Avatar Aang: The Last Airbender,en,"[16, 28, 12, 14]","Avatar Aang, the world's last Airbender, learn...",2026-07-24,303.9461,9.400,477
1,1632181,Accidental Partners,Socias por accidente,es,"[35, 10749]",Two women discover they were both scammed by t...,2026-03-12,28.9079,8.976,330
2,1007757,Swapped,Swapped,en,"[12, 16, 10751, 14]","A small woodland creature and a majestic bird,...",2026-05-01,70.1201,8.892,2023
3,278,The Shawshank Redemption,The Shawshank Redemption,en,"[18, 80]",Imprisoned in the 1940s for the double murder ...,1994-09-23,93.1432,8.726,30887
4,936075,Michael,Michael,en,"[10402, 18]","The story of Michael Jackson, one of the most ...",2026-04-22,115.7425,8.694,3777

In [5]:
df1 = pd.DataFrame()

In [6]:
for i in range(1, 500):
    response = requests.get(f'https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={i}')
    temp_df = pd.DataFrame(response.json()['results'])[columns]
    df1 = pd.concat([df1, temp_df] ,ignore_index=True)

In [7]:
df1

,id,title,original_title,original_language,genre_ids,overview,release_date,popularity,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,Avatar Aang: The Last Airbender,en,"[16, 28, 12, 14]","Avatar Aang, the world's last Airbender, learn...",2026-07-24,303.9461,9.400,477
1,1632181,Accidental Partners,Socias por accidente,es,"[35, 10749]",Two women discover they were both scammed by t...,2026-03-12,28.9079,8.976,330
2,1007757,Swapped,Swapped,en,"[12, 16, 10751, 14]","A small woodland creature and a majestic bird,...",2026-05-01,70.1201,8.892,2023
3,278,The Shawshank Redemption,The Shawshank Redemption,en,"[18, 80]",Imprisoned in the 1940s for the double murder ...,1994-09-23,93.1432,8.726,30887
4,936075,Michael,Michael,en,"[10402, 18]","The story of Michael Jackson, one of the most ...",2026-04-22,115.7425,8.694,3777
...,...,...,...,...,...,...,...,...,...,...
9975,50135,Animals United,Konferenz der Tiere,de,"[16, 10751, 35]",A group of animals waiting for the annual floo...,2010-10-07,2.2194,5.620,349
9976,1249289,Alarum,Alarum,en,"[28, 80, 53]",Two married spies caught in the crosshairs of ...,2025-01-16,4.6888,5.619,411
9977,9586,The Bonfire of the Vanities,The Bonfire of the Vanities,en,"[35, 18]","After his mistress runs over a black teen, a W...",1990-12-21,2.6359,5.619,543
9978,14365,Killing Me Softly,Killing Me Softly,en,"[53, 80]",A woman grows suspicious of her controlling hu...,2002-05-10,3.4782,5.618,372
9979,10727,Darkness Falls,Darkness Falls,en,"[53, 27]",A vengeful spirit has taken the form of the To...,2003-01-24,2.3247,5.618,666

In [8]:
df1.to_csv("movies_metadata.csv")