<a href="https://www.kaggle.com/code/ahmedfakhar123/ml-14-web-scraping-for-machine-learning?scriptVersionId=339679106" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

---
# 🤖 ML Lab 05 — Web Scraping for Machine Learning

### ***Learn how to collect real-world datasets from websites using Python and BeautifulSoup***

---

# 📖 Introduction

In Machine Learning, not all data is available through **CSV files** or **APIs**. Many valuable datasets exist only on websites, making **Web Scraping** an essential skill for collecting real-world data.

Web Scraping is the process of automatically extracting information from web pages using Python. It allows you to gather data such as product details, news articles, job listings, sports statistics, and much more, which can then be used for data analysis and Machine Learning.

In this notebook, you'll learn how to scrape web pages using **Requests** and **BeautifulSoup**, extract the information you need, organize it into a **Pandas DataFrame**, and save it as a CSV file for future use.

> **Note:** Always respect a website's Terms of Service and `robots.txt` rules, and only scrape websites where it is permitted.

<div align="center">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8Xl2D-MF3Z7BotdpzZsadpqM4k_7JG56rSG-l3OkXEw&s=10" width=500>
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRh3I2yI7RuCJcS3CwK_cT3L6QAP7ctCmxd-C47ith1iQ&s=10" width=500>
</div>

---
# 📦 Importing Required Libraries

Before scraping any website, let's import the libraries we'll need.

In [1]:
import pandas as pd
import numpy as np

import requests
from bs4 import BeautifulSoup

---
# 🌐 Sending Our First Request

We'll send an HTTP GET request to the PakWheels website.

To reduce the chances of getting blocked, we'll include a User-Agent header that mimics a real browser.

In [2]:
headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/138.0.0.0 Safari/537.36"
    )
}
webpage = requests.get('https://www.pakwheels.com/used-cars/search/-/?q=bmw', headers=headers).text

> **💡 Note:**  
> Some websites block requests made by Python scripts and return a **403 Forbidden** error. If this happens, include a **User-Agent** header in your request to make it appear as though the request is coming from a web browser.

```python
import requests

headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/138.0.0.0 Safari/537.36"
    )
}

response = requests.get("YOUR_URL", headers=headers)
```

---
# 🍲 Parsing the HTML

Now let's convert the downloaded HTML into a BeautifulSoup object.

In [3]:
soup = BeautifulSoup(webpage, "lxml")

---
# 👀 Exploring the HTML

Printing the HTML helps us understand the page structure before scraping.

In [4]:
print(soup.prettify())

<html>
 <body>
  <div class="modal" id="safety_precautions">
   <div class="modal-dialog">
    <div class="modal-content">
     <div class="modal-header noborder pb0">
      <button aria-hidden="true" class="close" data-dismiss="modal" type="button">
       ×
      </button>
     </div>
     <div class="modal-body nomargin" style="padding: 0px 40px 10px;">
      <div class="tlc mb25">
       <img height="70px" src="https://wsa1.pakwheels.com/assets/tips-for-safe-deal-3813a40c4961570f7cf04bd9f4c8daa4fc49e2e86c577bcd4236aeef301db2b7.svg"/>
       <div class="mb0 fs18 generic-basic mt10 lhm fwm">
        Tips for Safe Deal
       </div>
      </div>
      <div class="d-flex align-center mb15">
       <img class="mr20" height="36px" src="https://wsa3.pakwheels.com/assets/tip-for-safe-deal-1-dbcc070d37c48c08ad825e2eeccce214cba97e9b1e60b7d6392db3a252181967.svg"/>
       <p class="fs16 nomargin">
        Never make payments in advance.
       </p>
      </div>
      <div class="d-flex align-center mb15">
       <img class="mr20" height="36px" src="https://wsa3.pakwheels.com/assets/tip-for-safe-deal-2-e6c802da09520fc7d23f385ba5900d2462d01c525ba0e14b91a8393289960faf.svg"/>
       <p class="fs16 nomargin">
        Do not share unnecessary personal information.
       </p>
      </div>
      <div class="d-flex align-center mb15">
       <img class="mr20" height="36px" src="https://wsa1.pakwheels.com/assets/tip-for-safe-deal-3-c0a6ffac8164e7338f5d60c142c7b95538f0aa1c9d7cdb885ea7bc43bf5ba30a.svg"/>
       <p class="fs16 nomargin">
        Report suspicious users to Pakwheels.
       </p>
      </div>
      <div class="d-flex align-center mb15">
       <img class="mr20" height="36px" src="https://wsa2.pakwheels.com/assets/tip-for-safe-deal-4-bdad3d527e117498aa0b2fbb28dbae8b64c941ae657e56d9bcc406a6754961c8.svg"/>
       <p class="fs16 nomargin">
        Use PakWheels Car Inspection Service to avoid fraud.
       </p>
      </div>
      <div class="tlc mt40 mb20">
       <button class="btn btn-primary btn-lg fwb fs14 col-md-4 float-none" data-dismiss="modal" id="continue_btn" onclick=' $.cookie("chat_precaution", "true", { path: "/" }); trackEvents("used_cars","Continue","SafetyTipsSlider"); ' style="float: unset;">
        Continue
       </button>
      </div>
     </div>
    </div>
   </div>
  </div>
  <script>
   async function getSellerContactInfo(url) {
    return fetch(url)
      .then(res => res.json())
      .then(data => {
        if (data.error) {
          alert(data.error)
          return
        }

        phone_numbers = [data.phone, data.phone_1].filter(x => x) // Remove nulls
        phone_numbers = [... new Set(phone_numbers)].join(', ') // Unique and Join

        return {
          ...data,
          phone_numbers
        }
      })
  }
  async function incrementPhoneCount(url){
    $.ajax({
        type: 'POST',
        url: url
    });
  }
  function showChatPopup() {
    $("#contact_seller_div").modal(true);
  }

  function showMessagePop() {
    $('#continue_btn').click(showChatPopup);
    $("#safety_precautions").modal(true);
  }

  async function renderStickyPanelNumber() {
    var btn =  $('.btn-phone')
    var is_logged_in = btn.data().isLoggedIn;

    if(shouldShowSignInPopUp(is_logged_in)) {
        showSignInPopUp();
        return;
    }

    var data = await getSellerContactInfo(btn.data().sellerInfoUrl)

    if (!data)
      return

    btn.html('<i class=\'fa fa-phone\'></i> ' + data.phone_numbers);
    btn.addClass('active');

    contactPhoneEventTrack();
    adPhoneCount(btn.data().countPath);
    incrementPhoneNumberClickCount();
  }

  $('#safety_precautions').on('hide.bs.modal', function () {
    if (typeof (showChatPopup) === "function") $('#continue_btn').unbind("click", showChatPopup);
    if (typeof (showPhoneNumber) === "function") $('#continue_btn').unbind("click", showPhoneNumber);
    if (typeof (renderStickyPanelNumber) === "function") $('#continue_btn').unbind("click", renderStickyPanelNumber);
    $('#safety_precautions').unbind("click");
  });

  function showSidebarNumber()
  {
    $('#sign_in_pop_up').modal('show');
  }

  function showStickyPanelNumber() {
    $('#sign_in_pop_up').modal('show');
  }

  async function showStickyPanelNumberForWhatsapp(sellerInfoUrl, gaEventParams) {
      $('#sign_in_pop_up').modal('show');
  }

  async function showSearchListingNumberPopover(item) {
    var item = $(item);

    var data = await getSellerContactInfo(item.data().sellerInfoUrl);

    if (!data)
      return

    item.popover(
      {
        content: `
          <div class='text-center owner-info-popover'>
            <div class='primary-lang'>${data.name}</div>
            <h4 style='display:inline-block' class='nomargin mt5 generic-green primary-lang'><i class='fa fa-phone'></i> ${data.phone_numbers} </h4>
            <p style='margin:10px -15px 0' class='fs12'>Mention PakWheels.com when calling Seller to get a good deal</p>
          </div>
        `
    }).popover('show');

    if (!item.is(':focus')) {
      item.focus();
    }
  }

  function showSearchLisitngNumber(item) {
      // Destroy any existing popover to avoid showing stale phone numbers on focus
      try { $(item).popover('destroy'); } catch (e) {}
      $(item).blur();

      $('#sign_in_pop_up').modal('show');
  }

  async function showPhoneNumberInGallery(gallery_selector, seller_info_url) {
      $("#lg-outer").show();

      var data = await getSellerContactInfo(seller_info_url);
      var content = `
        <strong>
          ${data.name}
          <span class="generic-green fs16">${data.phone_numbers}</span>
        </strong>
      `

      $('.lg-slide.loaded .ad-show-btn').hide();
      $(gallery_selector + '.ad-show-btn').hide();

      var slide_numbers = $('.lg-slide.loaded .ad-numbers')
      var gallery_numbers = $(gallery_selector+'.ad-numbers')

      slide_numbers.html(content);
      gallery_numbers.html(content);

      slide_numbers.show();
      gallery_numbers.show();
  }

  function handlePhoneClickOnGallery(gallery_selector, seller_info_url){
    if ($.cookie("chat_precaution") == undefined) {
      $('#continue_btn').on("click", function () {
        $("#safety_precautions").modal('hide');
         showPhoneNumberInGallery(gallery_selector, seller_info_url)
      });

      $("#safety_precautions").modal(true);
      $("#safety_precautions").css('z-index', 99999);
    } else {
      showPhoneNumberInGallery(gallery_selector, seller_info_url)
    }
  }
  </script>
  <section>
   <div class="container">
    <script type="application/ld+json">
     {
  "@context": "http://schema.org",
  "@type": "ItemList",
  "url": "https://www.pakwheels.com/used-cars/search/-/?q=bmw",
  "numberOfItems": 25,
  "itemListOrder": "http://schema.org/ItemListUnordered",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "url": "https://www.pakwheels.com/used-cars/bmw-2-series-2021-for-sale-in-islamabad-11801241",
      "image": "https://cache2.pakwheels.com/ad_pictures/1484/bmw-2-series-218i-gran-coupe-2021-148413773.jpg",
      "name": "BMW 2 Series 2021 for sale in Islamabad"
    },
    {
      "@type": "ListItem",
      "position": 2,
      "url": "https://www.pakwheels.com/used-cars/bmw-i4-2022-for-sale-in-lahore-11804450",
      "image": "https://cache1.pakwheels.com/ad_pictures/1484/bmw-i4-edrive40-2022-148462138.jpg",
      "name": "BMW i4 2022 for sale in Lahore"
    },
    {
      "@type": "ListItem",
      "position": 3,
      "url": "https://www.pakwheels.com/used-cars/bmw-x1-2017-for-sale-in-lahore-11801722",
      "image": "https://cache4.pakwheels.com/ad_pictures/1484/bmw-x1-series-sdrive18i-a-t-2017-148422050.jpg",
      "name": "BMW X1 2017 for sale in Lahore"
    },
    {
      "@type": "ListItem",
      "position": 4,
      "url": "https://www.pakwheels.com/used-cars/bmw-5-series-2006-for-sale-in-karachi-10920540",
      "image": "https://cache3.pakwheels.com/ad_pictures/1411/bmw-5-series-525i-2006-141188057.jpg",
      "name": "BMW 5 Series 2006 for sale in Karachi"
    },
    {
      "@type": "ListItem",
      "position": 5,
      "url": "https://www.pakwheels.com/used-cars/bmw-3-series-2018-for-sale-in-lahore-11719463",
      "image": "https://cache1.pakwheels.com/ad_pictures/1471/bmw-3-series-316i-2018-147157384.jpg",
      "name": "BMW 3 Series 2018 for sale in Lahore"
    },
    {
      "@type": "ListItem",
      "position": 6,
      "url": "https://www.pakwheels.com/used-cars/bmw-x1-2018-for-sale-in-islamabad-11802382",
      "image": "https://cache1.pakwheels.com/ad_pictures/1484/bmw-x1-series-sdrive18i-a-t-2018-148431388.jpg",
      "name": "BMW X1 2018 for sale in Islamabad"
    },
    {
      "@type": "ListItem",
      "position": 7,
      "url": "https://www.pakwheels.com/used-cars/bmw-x3-2008-for-sale-in-karachi-11799864",
      "image": "https://cache3.pakwheels.com/ad_pictures/1483/bmw-x3-series-2008-148390900.jpg",
      "name": "BMW X3 2008 for sale in Karachi"
    },
    {
      "@type": "ListItem",
      "position": 8,
      "url": "https://www.pakwheels.com/used-cars/toyota-yaris-hatchback-2021-for-sale-in-islamabad-11800562",
      "image": "https://cache1.pakwheels.com/ad_pictures/1483/toyota-yaris-hatchback-x-50-2021-148398881.jpg",
      "name": "Toyota Yaris Hatchback 2021 for sale in Islamabad"
    },
    {
      "@type": "ListItem",
      "position": 9,
      "url": "https://www.pakwheels.com/used-cars/bmw-2-series-2020-for-sale-in-lahore-11710223",
      "image": "https://cache1.pakwheels.com/ad_pictures/1470/bmw-2-series-218i-gran-coupe-2020-147014342.jpg",
      "name": "BMW 2 Series 2020 for sale in Lahore"
    },
    {
      "@type": "ListItem",
      "position": 10,
      "url": "https://www.pakwheels.com/used-cars/bmw-7-series-2014-for-sale-in-lahore-11799995",
      "image": "https://cache4.pakwheels.com/ad_pictures/1483/bmw-7-series-750i-2-2014-148392830.jpg",
      "name": "BMW 7 Series 2014 for sale in Lahore"
    },
    {
      "@type": "ListItem",
      "position": 11,
      "url": "https://www.pakwheels.com/used-cars/bmw-x1-2017-for-sale-in-karachi-11777033",
      "image": "https://cache1.pakwheels.com/ad_pictures/1480/bmw-x1-series-sdrive18i-a-t-2017-148043145.jpg",
      "name": "BMW X1 2017 for sale in Karachi"
    },
    {
      "@type": "ListItem",
      "position": 12,
      "url": "https://www.pakwheels.com/used-cars/bmw-i4-2026-for-sale-in-lahore-11671471",
      "image": "https://cache3.pakwheels.com/ad_pictures/1464/bmw-i4-edrive35-2026-146419070.jpg",
      "name": "BMW i4 2026 for sale in Lahore"
    },
    {
      "@type": "ListItem",
      "position": 13,
      "url": "https://www.pakwheels.com/used-cars/bmw-3-series-1996-for-sale-in-peshawar-11543441",
      "image": "https://cache2.pakwheels.com/ad_pictures/1444/bmw-3-series-1996-144499267.jpg",
      "name": "BMW 3 Series 1996 for sale in Peshawar"
    },
    {
      "@type": "ListItem",
      "position": 14,
      "url": "https://www.pakwheels.com/used-cars/bmw-5-series-2004-for-sale-in-lahore-11802256",
      "image": "https://cache4.pakwheels.com/ad_pictures/1484/bmw-5-series-525i-2004-148430082.jpg",
      "name": "BMW 5 Series 2004 for sale in Lahore"
    },
    {
      "@type": "ListItem",
      "position": 15,
      "url": "https://www.pakwheels.com/used-cars/toyota-hilux-2014-for-sale-in-karachi-11570192",
      "image": "https://cache1.pakwheels.com/ad_pictures/1449/toyota-hilux-invincible-2014-144900489.jpg",
      "name": "Toyota Hilux 2014 for sale in Karachi"
    },
    {
      "@type": "ListItem",
      "position": 16,
      "url": "https://www.pakwheels.com/used-cars/bmw-7-series-2009-for-sale-in-islamabad-11785820",
      "image": "https://cache1.pakwheels.com/ad_pictures/1481/bmw-7-series-740i-2009-148176905.jpg",
      "name": "BMW 7 Series 2009 for sale in Islamabad"
    },
    {
      "@type": "ListItem",
      "position": 17,
      "url": "https://www.pakwheels.com/used-cars/bmw-x1-2017-for-sale-in-lahore-11751935",
      "image": "https://cache2.pakwheels.com/ad_pictures/1478/bmw-x1-series-sdrive18i-a-t-2017-147835501.jpg",
      "name": "BMW X1 2017 for sale in Lahore"
    },
    {
      "@type": "ListItem",
      "position": 18,
      "url": "https://www.pakwheels.com/used-cars/bmw-x1-2017-for-sale-in-karachi-11801566",
      "image": "https://cache3.pakwheels.com/ad_pictures/1484/bmw-x1-series-sdrive18i-a-t-2017-148418671.jpg",
      "name": "BMW X1 2017 for sale in Karachi"
    },
    {
      "@type": "ListItem",
      "position": 19,
      "url": "https://www.pakwheels.com/used-cars/bmw-3-series-2000-for-sale-in-lahore-11800300",
      "image": "https://cache3.pakwheels.com/ad_pictures/1483/bmw-3-series-316i-2000-148377270.jpg",
      "name": "BMW 3 Series 2000 for sale in Lahore"
    },
    {
      "@type": "ListItem",
      "position": 20,
      "url": "https://www.pakwheels.com/used-cars/bmw-x5-2014-for-sale-in-islamabad-11601960",
      "image": "https://cache4.pakwheels.com/ad_pictures/1453/bmw-x5-series-2014-145379274.jpg",
      "name": "BMW X5 2014 for sale in Islamabad"
    },
    {
      "@type": "ListItem",
      "position": 21,
      "url": "https://www.pakwheels.com/used-cars/bmw-7-series-2004-for-sale-in-lahore-11699191",
      "image": "https://cache2.pakwheels.com/ad_pictures/1468/bmw-7-series-745li-2004-146843287.jpg",
      "name": "BMW 7 Series 2004 for sale in Lahore"
    },
    {
      "@type": "ListItem",
      "position": 22,
      "url": "https://www.pakwheels.com/used-cars/bmw-3-series-2013-for-sale-in-lahore-11799011",
      "image": "https://cache4.pakwheels.com/ad_pictures/1483/bmw-3-series-316i-2013-148376327.jpg",
      "name": "BMW 3 Series 2013 for sale in Lahore"
    },
    {
      "@type": "ListItem",
      "position": 23,
      "url": "https://www.pakwheels.com/used-cars/bmw-x1-2017-for-sale-in-islamabad-11793484",
      "image": "https://cache4.pakwheels.com/ad_pictures/1482/bmw-x1-series-sdrive18i-a-t-2017-148291734.jpg",
      "name": "BMW X1 2017 for sale in Islamabad"
    },
    {
      "@type": "ListItem",
      "position": 24,
      "url": "https://www.pakwheels.com/used-cars/bmw-i5-2024-for-sale-in-gujranwala-11798127",
      "image": "https://cache1.pakwheels.com/ad_pictures/1483/bmw-i5-edrive40-m-sport-2024-148364979.jpg",
      "name": "BMW i5 2024 for sale in Gujranwala"
    },
    {
      "@type": "ListItem",
      "position": 25,
      "url": "https://www.pakwheels.com/used-cars/bmw-i5-2023-for-sale-in-islamabad-11409602",
      "image": "https://cache4.pakwheels.com/ad_pictures/1424/bmw-i5-edrive40-m-sport-2023-142420306.jpg",
      "name": "BMW i5 2023 for sale in Islamabad"
    }
  ]
}
    </script>
    <div class="modal" id="email_alert_div">
     <div class="modal-dialog">
      <div class="modal-content">
       <div class="modal-header">
        <button aria-hidden="true" class="close" data-dismiss="modal" onclick="$('#email_alert_div').modal('hide');" type="button">
         ×
        </button>
        <p class="fwm generic-blue mb0">
         Receive email notifications for the latest ads matching your search criteria
        </p>
       </div>
       <div class="modal-body seller-form">
        <form accept-charset="UTF-8" action="/alerts" class="form-horizontal" data-parsley-validate="" id="popup_alert" method="post">
         <input name="utf8" type="hidden" value="✓"/>
         <input name="authenticity_token" type="hidden" value="aCw6rm4+z8+jQ3arryLYjZWLS8Sxs2kGZzhRstlvuARShVRPb62IJip67NypzZ+MlsGx8sxXF6cWUEEZY2qncQ=="/>
         <div class="form-group">
          <label class="col-md-4">
           Email
           <span class="text-error">
            *
           </span>
           :
          </label>
          <div class="col-md-8">
           <input data-parsley-required="true" data-parsley-type="email" id="email" maxlength="100" name="email" onchange="$('#user_email').val($(this).val());$('#user_email_alert_box').val($(this).val())" placeholder="Type your email address" type="text" value=""/>
          </div>
         </div>
         <input id="alert_filters" name="alert[filters]" type="hidden" value="/used-cars/search/-/?q=bmw"/>
         <div class="form-group">
          <label class="col-md-4">
           Mobile Number:
          </label>
          <div class="col-md-8">
           <input data-parsley-error-message="Enter valid number" data-parsley-pattern="^[0-9]{7,}$" data-parsley-trigger="change" id="phone_number" maxlength="15" name="phone_number" placeholder="Type your mobile number" type="text" value=""/>
          </div>
         </div>
         <div class="form-group">
          <label class="col-md-4">
           Frequency:
          </label>
          <div class="col-md-8">
           <select id="alert_duration" name="alert[duration]">
            <option value="1">
             Daily
            </option>
            <option value="7">
             Weekly
            </option>
           </select>
          </div>
         </div>
        </form>
       </div>
       <div class="modal-footer">
        <div class="pull-right">
         <input class="btn btn-primary" name="commit" onclick="if($('#popup_alert').parsley('isValid')){trackEvents('UsedCars', 'Create Alert', 'From - Search');addToJStorage('car');$('#popup_alert').submit();}" type="submit" value="Create Alert"/>
        </div>
       </div>
      </div>
     </div>
    </div>
    <div id="fb-root">
    </div>
    <div class="used-car-search-results" data-pjax-container="">
     <input id="dfp_city" name="dfp_city" type="hidden"/>
     <input id="dfp_make" name="dfp_make" type="hidden"/>
     <input id="dfp_model" name="dfp_model" type="hidden"/>
     <h1 style="line-height: 20px">
      Used Cars For Sale In Pakistan
     </h1>
     <div class="search-count-wrapper">
      <ul class="breadcrumb" itemscope="itemscope" itemtype="https://schema.org/BreadcrumbList">
       <li itemprop="itemListElement" itemscope="itemscope" itemtype="https://schema.org/ListItem">
        <a href="/" itemprop="url">
         <span itemprop="name">
          Home
         </span>
        </a>
        <meta content="https://www.pakwheels.com/" itemprop="item"/>
        <meta content="1" itemprop="position"/>
       </li>
       <li itemprop="itemListElement" itemscope="itemscope" itemtype="https://schema.org/ListItem">
        <a href="/used-cars/" itemprop="url">
         <span itemprop="name">
          Used Cars
         </span>
        </a>
        <meta content="https://www.pakwheels.com/used-cars/" itemprop="item"/>
        <meta content="2" itemprop="position"/>
       </li>
       <li class="active" itemprop="itemListElement" itemscope="itemscope" itemtype="https://schema.org/ListItem">
        <span itemprop="name">
         Used Cars For Sale In Pakistan
        </span>
        <meta content="3" itemprop="position"/>
       </li>
      </ul>
      <div class="search-pagi-info">
       <b>
        1 - 24
       </b>
       of
       <b>
        309
       </b>
       Results
      </div>
     </div>
     <div class="search-page-new">
      <div class="row">
       <div class="col-md-3 used-car-refine-search">
        <div class="sidebar-filters">
         <div class="filter-panel-new box" data-pjax-enable="">
          <input id="selected_city_slug" name="selected_city_slug" type="hidden"/>
          <input id="query_filter" name="query_filter" type="hidden" value="bmw"/>
          <div class="accordion" id="sidebar">
           <div class="accordion-group search-filter-heading">
            <div class="accordion-heading">
             <a class="accordion-toggle">
              Show Results By:
             </a>
            </div>
           </div>
           <div class="accordion-group">
            <div class="accordion-heading">
             <a class="accordion-toggle" data-toggle="collapse" href="#collapse_search_key_keyword">
              <i class="fa fa-caret-down">
              </i>

---
# 🔍 Extracting Car Titles

Let's extract all BMW car names.

In [5]:
for title in soup.find_all("h3", style="white-space: normal;"):
    print(title.text.strip())

BMW 2 Series  2021 218i Gran Coupe for Sale
BMW i4  2022 eDrive40 for Sale
BMW X1  2017 sDrive18i A/T for Sale
BMW 5 Series 5th (E60) Generation 2006 525i for Sale
BMW 3 Series  2018 318i for Sale
BMW X1  2018 sDrive18i A/T for Sale
BMW X3  2008  for Sale
Toyota Yaris Hatchback  2021 X for Sale
BMW 2 Series  2020 218i Gran Coupe for Sale
BMW 7 Series  2014 750i for Sale
BMW X1  2017 sDrive18i A/T for Sale
BMW i4  2026 eDrive35 for Sale
BMW 3 Series  1996  for Sale
BMW 5 Series 5th (E60) Generation 2004 525i for Sale
Toyota Hilux  2014 Invincible for Sale
BMW 7 Series 5th (F01) Generation 2009 740i for Sale
BMW X1  2017 sDrive18i A/T for Sale
BMW X1  2017 sDrive18i A/T for Sale
BMW 3 Series 4th (E46) Generation 2000 316i for Sale
BMW X5  2014  for Sale
BMW 7 Series 4th (E65) Generation 2004 745Li for Sale
BMW 3 Series  2013 316i for Sale
BMW X1  2017 sDrive18i A/T for Sale
BMW i5  2024 eDrive40 M Sport for Sale
BMW i5  2023 eDrive40 M Sport for Sale

---
# 🚘 Finding All Car Listings

Each listing is stored inside a `<div>` element with the class well.

In [6]:
all_cars = soup.find_all("div", class_="well")

In [7]:
len(all_cars)

29

---
# 📝 Creating Empty Lists

We'll store every attribute inside a separate list before creating our DataFrame.

In [8]:
name = []
price = []
rating = []
year = []
mileage = []
fuel_type = []
engine = []
transmission = []

---

# 🔄 Scraping One Page

Now we'll extract information from every listing on the current page.

In [9]:
for car in all_cars:
    if car.find("h3") is None:
        continue
    try:
        # Car Name
        name.append(car.find("h3").get_text(strip=True))
    except:
        name.append(np.nan)

    try:
        # Price
        price.append(car.find("div", class_="price-details").get_text(strip=True))
    except:
        price.append(np.nan)

    try:
        # Auction Rating
        rating.append(car.find("span", class_="auction-rating").get_text(strip=True))
    except:
        rating.append(np.nan)

    try:
        specs = car.find("ul", class_="list-unstyled search-vehicle-info-2 fs13").find_all("li")

        if len(specs) >= 5:
            year.append(specs[0].get_text(strip=True))
            mileage.append(specs[1].get_text(strip=True))
            fuel_type.append(specs[2].get_text(strip=True))
            engine.append(specs[3].get_text(strip=True))
            transmission.append(specs[4].get_text(strip=True))

    except:
        year.append(np.nan)
        mileage.append(np.nan)
        fuel_type.append(np.nan)
        engine.append(np.nan)
        transmission.append(np.nan)

---
# 📊 Creating the Dataset

Let's convert the extracted lists into a Pandas DataFrame

In [10]:
cars_df = pd.DataFrame({
    "Car Name": name,
    "Price": price,
    "Auction Rating": rating,
    "Model Year": year,
    "Mileage": mileage,
    "Fuel Type": fuel_type,
    "Engine Capacity": engine,
    "Transmission": transmission,
})
cars_df

,Car Name,Price,Auction Rating,Model Year,Mileage,Fuel Type,Engine Capacity,Transmission
0,BMW 2 Series 2021 218i Gran Coupe for Sale,PKR 1.35crore,9.3/10,2021,"68,064 km",Petrol,1500 cc,Manual
1,BMW i4 2022 eDrive40 for Sale,PKR 2.09crore,NaN,2022,"41,500 km",Electric,84.0 kWh,Automatic
2,BMW X1 2017 sDrive18i A/T for Sale,PKR 72lacs,8.7/10,2017,"89,293 km",Petrol,1500 cc,Automatic
3,BMW 5 Series 5th (E60) Generation 2006 525i fo...,PKR 40lacs,8/10,2006,"89,383 km",Petrol,2500 cc,Automatic
4,BMW 3 Series 2018 318i for Sale,PKR 90lacs,8.3/10,2018,"109,245 km",Petrol,1600 cc,Automatic
5,BMW X1 2018 sDrive18i A/T for Sale,PKR 95lacs,NaN,2018,"150,000 km",Petrol,1500 cc,Automatic
6,BMW X3 2008 for Sale,PKR 40lacs,7.3/10,2008,"93,048 km",Petrol,2500 cc,Automatic
7,Toyota Yaris Hatchback 2021 X for Sale,PKR 47.9lacs,NaN,2021,"80,000 km",Petrol,1000 cc,Automatic
8,BMW 2 Series 2020 218i Gran Coupe for Sale,PKR 1.5crore,9.3/10,2020,"25,441 km",Petrol,1500 cc,Manual
9,BMW 7 Series 2014 750i for Sale,Call,NaN,2014,"48,000 km",Petrol,4400 cc,Automatic
10,BMW X1 2017 sDrive18i A/T for Sale,PKR 90lacs,9.1/10,2017,"30,005 km",Petrol,1500 cc,Automatic
11,BMW i4 2026 eDrive35 for Sale,PKR 2.55crore,NaN,2026,"1,500 km",Electric,67.0 kWh,Automatic
12,BMW 3 Series 1996 for Sale,PKR 21lacs,NaN,1996,"200,000 km",Petrol,1800 cc,Manual
13,BMW 5 Series 5th (E60) Generation 2004 525i fo...,PKR 28lacs,NaN,2004,"150,000 km",Petrol,2500 cc,Automatic
14,Toyota Hilux 2014 Invincible for Sale,PKR 78.5lacs,NaN,2014,"117,000 km",Diesel,3000 cc,Automatic
15,BMW 7 Series 5th (F01) Generation 2009 740i fo...,PKR 84.5lacs,NaN,2009,"84,000 km",Petrol,3000 cc,Automatic
16,BMW X1 2017 sDrive18i A/T for Sale,PKR 72.5lacs,NaN,2017,"125,000 km",Petrol,1500 cc,Automatic
17,BMW X1 2017 sDrive18i A/T for Sale,PKR 56lacs,NaN,2017,"130,000 km",Petrol,1500 cc,Automatic
18,BMW 3 Series 4th (E46) Generation 2000 316i fo...,PKR 22lacs,NaN,2000,"155,000 km",Petrol,1800 cc,Manual
19,BMW X5 2014 for Sale,PKR 1.6crore,7.6/10,2014,"83,980 km",Diesel,2000 cc,Automatic
20,BMW 7 Series 4th (E65) Generation 2004 745Li f...,PKR 35lacs,NaN,2004,"174,580 km",Petrol,4400 cc,Automatic
21,BMW 3 Series 2013 316i for Sale,PKR 99lacs,NaN,2013,"69,000 km",Petrol,1600 cc,Automatic
22,BMW X1 2017 sDrive18i A/T for Sale,Call,NaN,2017,"150,000 km",Petrol,1500 cc,Automatic
23,BMW i5 2024 eDrive40 M Sport for Sale,PKR 2.56crore,NaN,2024,"6,100 km",Electric,81.0 kWh,Automatic
24,BMW i5 2023 eDrive40 M Sport for Sale,PKR 3crore,NaN,2023,"4,000 km",Electric,8120.0 kWh,Automatic

---
# 🚀 Scraping Multiple Pages

Instead of collecting data from only one page, we can loop through all available pages.

In [11]:
all_cars_df = pd.DataFrame()

for page in range(1, 12):
    headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/138.0.0.0 Safari/537.36"
    )}
    webpage = requests.get(f'https://www.pakwheels.com/used-cars/search/-/mk_bmw/?page={page}', headers=headers).text

    soup = BeautifulSoup(webpage, "lxml")

    all_cars = soup.find_all("div", class_="well")

    name = []
    price = []
    rating = []
    year = []
    mileage = []
    fuel_type = []
    engine = []
    transmission = []

    for car in all_cars:
        if car.find("h3") is None:
            continue
        try:
            # Car Name
            name.append(car.find("h3").get_text(strip=True))
        except:
            name.append(np.nan)

        try:
            # Price
            price.append(car.find("div", class_="price-details").get_text(strip=True))
        except:
            price.append(np.nan)

        try:
            # Auction Rating
            rating.append(car.find("span", class_="auction-rating").get_text(strip=True))
        except:
            rating.append(np.nan)

        try:
            specs = car.find("ul", class_="list-unstyled search-vehicle-info-2 fs13").find_all("li")

            if len(specs) >= 5:
                year.append(specs[0].get_text(strip=True))
                mileage.append(specs[1].get_text(strip=True))
                fuel_type.append(specs[2].get_text(strip=True))
                engine.append(specs[3].get_text(strip=True))
                transmission.append(specs[4].get_text(strip=True))

        except:
            year.append(np.nan)
            mileage.append(np.nan)
            fuel_type.append(np.nan)
            engine.append(np.nan)
            transmission.append(np.nan)

        current_cars_df = pd.DataFrame({
        "Car Name": name,
        "Price": price,
        "Auction Rating": rating,
        "Model Year": year,
        "Mileage": mileage,
        "Fuel Type": fuel_type,
        "Engine Capacity": engine,
        "Transmission": transmission,
        })

    all_cars_df = pd.concat([all_cars_df, current_cars_df], ignore_index=True)

In [12]:
all_cars_df

,Car Name,Price,Auction Rating,Model Year,Mileage,Fuel Type,Engine Capacity,Transmission
0,BMW 2 Series 2021 218i Gran Coupe for Sale,PKR 1.35crore,9.3/10,2021,"68,064 km",Petrol,1500 cc,Manual
1,BMW i4 2022 eDrive40 for Sale,PKR 2.09crore,NaN,2022,"41,500 km",Electric,84.0 kWh,Automatic
2,BMW X1 2017 sDrive18i A/T for Sale,PKR 72lacs,8.7/10,2017,"89,293 km",Petrol,1500 cc,Automatic
3,BMW 5 Series 5th (E60) Generation 2006 525i fo...,PKR 40lacs,8/10,2006,"89,383 km",Petrol,2500 cc,Automatic
4,BMW 3 Series 2018 318i for Sale,PKR 90lacs,8.3/10,2018,"109,245 km",Petrol,1600 cc,Automatic
...,...,...,...,...,...,...,...,...
353,BMW 3 Series 2013 for Sale,PKR 80lacs,NaN,2013,"70,000 km",Petrol,1600 cc,Manual
354,BMW M5 2019 for Sale,PKR 4.55crore,NaN,2019,"59,000 km",Petrol,4400 cc,Automatic
355,BMW X6 2009 for Sale,PKR 1.6crore,NaN,2009,"104,000 km",Diesel,3000 cc,Automatic
356,BMW 3 Series 1980 for Sale,PKR 90lacs,NaN,1980,2 km,Petrol,4400 cc,Automatic
357,BMW 7 Series 2024 i7 xDrive50 M Sport for Sale,PKR 6.2crore,NaN,2024,"10,600 km",Electric,100.0 kWh,Automatic

---
# 🔄 Converting Data Types

The scraped data is currently stored as **`object` (string)** because websites return almost all values as text. However, machine learning models and data analysis require numerical values for calculations, filtering, and visualization.

In this step, we'll convert each column to its appropriate data type by cleaning unnecessary text (such as `PKR`, `km`, `cc`, and `/10`) and transforming the values into numeric or categorical formats.

### Changes Made

| Column          | Current | Will be           |
| --------------- | ------- | ------------------- |
| Car Name        | object  | object              |
| Price           | object  | numeric (float/int) |
| Auction Rating  | object  | float               |
| Model Year      | object  | int                 |
| Mileage         | object  | int                 |
| Fuel Type       | object  | category/object     |
| Engine Capacity | object  | numeric             |
| Transmission    | object  | category/object     |


After these conversions, the dataset becomes cleaner, more memory-efficient, and ready for preprocessing, exploratory data analysis (EDA), and machine learning.

## 1. Model Year → int

In [13]:
all_cars_df["Model Year"] = pd.to_numeric(
    all_cars_df["Model Year"],
    errors="coerce"
).astype("Int64")

## 2. Auction Rating → float

In [14]:
all_cars_df["Auction Rating"] = (
    all_cars_df["Auction Rating"]
    .str.replace("/10", "", regex=False)
)

all_cars_df["Auction Rating"] = pd.to_numeric(
    all_cars_df["Auction Rating"],
    errors="coerce"
)

## 3. Mileage → int

In [15]:
all_cars_df["Mileage"] = (
    all_cars_df["Mileage"]
    .str.replace(",", "", regex=False)
    .str.replace(" km", "", regex=False)
)

all_cars_df["Mileage"] = pd.to_numeric(
    all_cars_df["Mileage"],
    errors="coerce"
).astype("Int64")

## 4. Engine Capacity

This one is tricky because we have
```
1600 cc
1500 cc
81.0 kWh
710.0 kWh
```
Since EVs use kWh and fuel cars use cc, we don't combine them into one numeric column.

In [16]:
all_cars_df["Engine Unit"] = (
    all_cars_df["Engine Capacity"]
    .str.extract(r'(cc|kWh)')
)

all_cars_df["Engine Capacity"] = (
    all_cars_df["Engine Capacity"]
    .str.extract(r'([\d.]+)')
)

all_cars_df["Engine Capacity"] = pd.to_numeric(
    all_cars_df["Engine Capacity"],
    errors="coerce"
)

## 5. Price

In [17]:
def convert_price(price):
    if pd.isna(price):
        return None

    price = price.lower().replace("pkr", "").strip()

    if "crore" in price:
        return float(price.replace("crore", "")) * 10_000_000

    elif "lac" in price:
        price = price.replace("lacs", "").replace("lac", "")
        return float(price) * 100_000

    return None

all_cars_df["Price (PKR)"] = all_cars_df["Price"].apply(convert_price)

all_cars_df.drop("Price", inplace=True, axis=1)

## 6. Fuel Type & Transmission

In [18]:
all_cars_df["Fuel Type"] = all_cars_df["Fuel Type"].astype("category")
all_cars_df["Transmission"] = all_cars_df["Transmission"].astype("category")

In [19]:
all_cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 358 entries, 0 to 357
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Car Name         358 non-null    object
 1   Auction Rating   26 non-null     float64
 2   Model Year       358 non-null    Int64
 3   Mileage          358 non-null    Int64
 4   Fuel Type        358 non-null    category
 5   Engine Capacity  358 non-null    float64
 6   Transmission     358 non-null    category
 7   Engine Unit      358 non-null    object
 8   Price (PKR)      307 non-null    float64
dtypes: Int64(2), category(2), float64(3), object(2)
memory usage: 21.4+ KB

---
# 🎉 Final Scraped Dataset

The complete dataset has now been collected by combining data from all scraped pages into a single Pandas DataFrame.

In [20]:
all_cars_df

,Car Name,Auction Rating,Model Year,Mileage,Fuel Type,Engine Capacity,Transmission,Engine Unit,Price (PKR)
0,BMW 2 Series 2021 218i Gran Coupe for Sale,9.3,2021,68064,Petrol,1500.0,Manual,cc,13500000.0
1,BMW i4 2022 eDrive40 for Sale,NaN,2022,41500,Electric,84.0,Automatic,kWh,20900000.0
2,BMW X1 2017 sDrive18i A/T for Sale,8.7,2017,89293,Petrol,1500.0,Automatic,cc,7200000.0
3,BMW 5 Series 5th (E60) Generation 2006 525i fo...,8.0,2006,89383,Petrol,2500.0,Automatic,cc,4000000.0
4,BMW 3 Series 2018 318i for Sale,8.3,2018,109245,Petrol,1600.0,Automatic,cc,9000000.0
...,...,...,...,...,...,...,...,...,...
353,BMW 3 Series 2013 for Sale,NaN,2013,70000,Petrol,1600.0,Manual,cc,8000000.0
354,BMW M5 2019 for Sale,NaN,2019,59000,Petrol,4400.0,Automatic,cc,45500000.0
355,BMW X6 2009 for Sale,NaN,2009,104000,Diesel,3000.0,Automatic,cc,16000000.0
356,BMW 3 Series 1980 for Sale,NaN,1980,2,Petrol,4400.0,Automatic,cc,9000000.0
357,BMW 7 Series 2024 i7 xDrive50 M Sport for Sale,NaN,2024,10600,Electric,100.0,Automatic,kWh,62000000.0

---
# 💾 Saving the Dataset

Finally, save the scraped data for future analysis or Machine Learning projects.

In [21]:
all_cars_df.to_csv("bmw_cars_pakistan.csv")

---
# 🎯 Conclusion

Congratulations! 🎉 In this notebook, you learned how to collect real-world data by scraping the PakWheels website using **Requests** and **BeautifulSoup**. Starting from sending HTTP requests with browser headers to parsing HTML, extracting useful information, and combining data from multiple pages into a single DataFrame, you've built a complete web scraping workflow.

The final dataset is now ready for the next stages of the data science pipeline, including **data cleaning, exploratory data analysis (EDA), feature engineering, and machine learning**. Web scraping is a valuable skill that enables you to gather custom datasets when publicly available data isn't sufficient for your projects.

Keep in mind that website structures can change over time, so scraping code may need updates. Always respect a website's terms of service and scrape responsibly. 🚀

---
# 🚀 What's Next?

[**🤖 ML 15 — Automated EDA with YData Profiling**](https://www.kaggle.com/code/ahmedfakhar123/ml-15-automated-eda-with-ydata-profiling)

Awesome work! 🎉 You've successfully collected real-world data through web scraping. Now it's time to explore your dataset automatically and uncover insights in just a few lines of code.

In the next notebook, you'll learn how to:

- 🤖 Generate a complete Exploratory Data Analysis (EDA) report automatically
- 📊 Explore dataset statistics, distributions, and correlations
- ❓ Detect missing values and duplicate records
- 📈 Analyze numerical and categorical features
- 🔍 Identify potential data quality issues
- ⚠️ Discover outliers and unusual patterns
- 🧠 Gain valuable insights before data preprocessing and model building

By the end, you'll be able to create professional, interactive EDA reports with **YData Profiling**, making dataset exploration faster, easier, and more insightful.

Happy Coding! 🚀