<a href="https://www.kaggle.com/code/ahmedfakhar123/ml-20-pipelines-in-scikit-learn?scriptVersionId=340535156" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

---

# 🤖 ML 20 — Pipelines in Scikit-learn

### ***Build clean and reusable machine learning workflows with Pipelines***

---


# 🚀 Introduction

As machine learning projects become more complex, managing multiple preprocessing steps and model training separately can make your code repetitive and difficult to maintain.

**Pipelines** in **Scikit-learn** solve this problem by chaining multiple steps—such as **data preprocessing**, **feature transformation**, and **model training**—into a single workflow. This makes your code cleaner, reduces the risk of data leakage, and ensures that the same preprocessing is consistently applied during both training and prediction.

In this notebook, you'll learn how to build machine learning pipelines in **Scikit-learn**, understand why they're important, and use them to create efficient, organized, and production-ready ML workflows with practical examples. 🚀

<div align="center">
    <img src="https://i.ytimg.com/vi/0qqYXsfifNk/maxresdefault.jpg" width=500>
    <img src="https://www.kdnuggets.com/wp-content/uploads/awan_streamline_machine_learning_workflow_scikitlearn_pipelines_4.png" width=500>
</div>

---

# 🎯 Why Use Pipelines?

Without pipelines, your workflow might look like this:

In [1]:
# Handle missing values
# Encode categorical data
# Scale features
# Train model
# Make predictions

As your project grows, this quickly becomes messy.

With a pipeline:

In [2]:
# pipeline.fit(X_train, y_train)
# predictions = pipeline.predict(X_test)

Everything happens automatically in the correct order.

---
# 🧩 What is a Pipeline?

A **Pipeline** is a sequence of transformers followed by a final estimator (machine learning model).



Each step passes its output to the next step.

In [3]:
'''
Raw Data
    │
    ▼
Missing Value Imputation
    │
    ▼
Encoding
    │
    ▼
Feature Scaling
    │
    ▼
Feature Selection (Optional)
    │
    ▼
Machine Learning Model
    │
    ▼
Predictions
'''

'\nRaw Data\n    │\n    ▼\nMissing Value Imputation\n    │\n    ▼\nEncoding\n    │\n    ▼\nFeature Scaling\n    │\n    ▼\nFeature Selection (Optional)\n    │\n    ▼\nMachine Learning Model\n    │\n    ▼\nPredictions\n'


---

# ✅ Advantages of Pipelines

* 🚀 Cleaner and more organized code
* 🔒 Prevents data leakage
* 🔁 Reproducible workflows
* 🛠 Easy to modify preprocessing steps
* 🎯 Works seamlessly with Cross Validation
* 🔍 Compatible with GridSearchCV and RandomizedSearchCV
* 📦 Easy to save and deploy


---

# 📚 Pipeline Components

A pipeline contains two kinds of steps.

### 1️⃣ Transformers

Transformers modify the input data.

Examples:

* SimpleImputer
* StandardScaler
* MinMaxScaler
* OneHotEncoder
* OrdinalEncoder
* PolynomialFeatures
* PCA

Transformers implement:

```python
fit()
transform()
fit_transform()
```


### 2️⃣ Estimator

The final step is the machine learning model.

Examples:

* LogisticRegression
* DecisionTreeClassifier
* RandomForestClassifier
* SVC
* LinearRegression
* KNeighborsClassifier

Estimators implement:

```python
fit()
predict()
score()
```

---

# 📦 Importing Libraries

In [4]:
import pandas as pd
import numpy as np

from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.compose import ColumnTransformer

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import (OneHotEncoder, MinMaxScaler)
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.tree import DecisionTreeClassifier

In [5]:
df = pd.read_csv("/kaggle/input/datasets/ahmedfakhar123/titanic-survival-dataset/Titanic_Survival_Dataset.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
df.drop(columns=["PassengerId", "Name", "Ticket", "Cabin"], inplace=True)
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [7]:
X = df.drop(columns=["Survived"])
y = df.Survived

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

---

# 🚀 Building the Machine Learning Pipeline

Instead of manually applying each preprocessing step one by one, we'll combine everything into a **single Scikit-learn Pipeline**. This ensures that every transformation is executed in the correct order during training and prediction.

Our pipeline will perform the following operations:

1. 🩹 Handle missing values
2. 🔤 Encode categorical features
3. 📏 Scale numerical features
4. 🎯 Select the most important features
5. 🌳 Train a Decision Tree classifier

This approach keeps the workflow clean, reusable, and helps prevent data leakage.


# 🩹 Step 1 — Handling Missing Values

Machine learning models cannot work directly with missing values (`NaN`). Before training, we need to replace them with meaningful values.

In this dataset:

* **Age** is filled using the **mean** value.
* **Embarked** is filled using the **most frequent** category.

In [9]:
# Step 1: Imputation
trf1 = ColumnTransformer([
    ('impute_age', SimpleImputer(), [2]),
    ('impute_embarked', SimpleImputer(strategy='most_frequent'), [6])
], remainder='passthrough')


# 🔤 Step 2 — Encoding Categorical Features

Machine learning algorithms require numerical input, but our dataset contains categorical features such as **Sex** and **Embarked**.

We'll use **One-Hot Encoding** to convert each category into separate binary columns while avoiding issues with unseen categories during prediction.

In [10]:
# Step 2: Encoding
trf2 = ColumnTransformer([
    ('encode_sex_embarked', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), [1, 3])
], remainder='passthrough')

# 📏 Step 3 — Feature Scaling

Features often have very different ranges.

For example:

* Age → around **20–80**
* Fare → can exceed **500**

We'll normalize the features using **MinMaxScaler**, which rescales values to the range **0–1**.

In [11]:
# Step 3: Scaling
trf3 = ColumnTransformer([
    ('scale', MinMaxScaler(), slice(0, 10)),
], remainder='passthrough')


# 🎯 Step 4 — Feature Selection

Not every feature contributes equally to predicting survival.

Using **SelectKBest** with the **Chi-Square (χ²)** statistical test, we'll automatically select the most informative features before training the model.

In [12]:
# Step 4: Feature Selection
trf4 = SelectKBest(score_func=chi2, k=8)

# 🌳 Step 5 — Machine Learning Model

Finally, we'll train a **Decision Tree Classifier** using the transformed features.

In [13]:
# Step 5: Machine Learning Model
trf5 = DecisionTreeClassifier()


# 🔗 Combining Everything into a Pipeline

Now we'll combine all preprocessing steps and the machine learning model into a single Pipeline.

From this point onward, calling **`fit()`** or **`predict()`** on the pipeline automatically executes every step in the correct order.

In [14]:
pipe = Pipeline([
    ('trf1', trf1),
    ('trf2', trf2),
    ('trf3', trf3),
    ('trf4', trf4),
    ('trf5', trf5)
])

# ⚡ Pipeline vs `make_pipeline()`

Scikit-learn provides two ways to create a pipeline.

### ✅ `Pipeline`

With `Pipeline`, you explicitly assign a name to every step.

```python
pipe = Pipeline([
    ("preprocessing", preprocessor),
    ("model", DecisionTreeClassifier())
])
```

**Advantages**

* Custom step names
* Easier debugging
* Required when referencing specific steps (e.g., GridSearchCV parameters)


### ✅ `make_pipeline()`

`make_pipeline()` automatically generates step names based on the estimator class names.

In [15]:
pipe = make_pipeline(trf1, trf2, trf3, trf4, trf5)


**Advantages**

* Less code
* Faster to write
* Great for quick experiments


### 📌 Which one should you use?

For educational notebooks and production projects, **`Pipeline` is generally preferred** because the custom step names make the workflow easier to understand and simplify hyperparameter tuning with `GridSearchCV`.


# 🎨 Visualizing the Pipeline

Scikit-learn can display pipelines as interactive diagrams, making it easier to understand how data flows through each preprocessing step before reaching the final model.

In [16]:
# Display Pipeline

from sklearn import set_config
set_config(display='diagram')

In [17]:
pipe

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('columntransformer-2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('encode_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 3])])),
                ('columntransformer-3',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('selectkbest',
                 SelectKBest(k=8,
                             score_func=<function chi2 at 0x79574d8e7e20>)),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

# 🚀 Training the Pipeline

Training the pipeline is as simple as training any other Scikit-learn model.

A single call to `fit()` performs every preprocessing step automatically before fitting the Decision Tree classifier.

In [18]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('columntransformer-2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('encode_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 3])])),
                ('columntransformer-3',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('selectkbest',
                 SelectKBest(k=8,
                             score_func=<function chi2 at 0x79574d8e7e20>)),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

# 🔍 Exploring the Pipeline

After training, you can inspect individual components using the `named_steps` attribute. This is useful for understanding the pipeline, debugging preprocessing steps, or accessing learned parameters.

In [19]:
pipe.named_steps

{'columntransformer-1': ColumnTransformer(remainder='passthrough',
                   transformers=[('impute_age', SimpleImputer(), [2]),
                                 ('impute_embarked',
                                  SimpleImputer(strategy='most_frequent'),
                                  [6])]),
 'columntransformer-2': ColumnTransformer(remainder='passthrough',
                   transformers=[('encode_sex_embarked',
                                  OneHotEncoder(handle_unknown='ignore',
                                                sparse_output=False),
                                  [1, 3])]),
 'columntransformer-3': ColumnTransformer(remainder='passthrough',
                   transformers=[('scale', MinMaxScaler(), slice(0, 10, None))]),
 'selectkbest': SelectKBest(k=8, score_func=<function chi2 at 0x79574d8e7e20>),
 'decisiontreeclassifier': DecisionTreeClassifier()}

For example, you can inspect the first `ColumnTransformer`:

In [20]:
pipe.named_steps['columntransformer-1']

ColumnTransformer(remainder='passthrough',
                  transformers=[('impute_age', SimpleImputer(), [2]),
                                ('impute_embarked',
                                 SimpleImputer(strategy='most_frequent'),
                                 [6])])

Or retrieve the most frequent value learned by the `SimpleImputer`:

In [21]:
pipe.named_steps['columntransformer-1'].transformers_[1][1].statistics_

array(['S'], dtype=object)

This demonstrates that a pipeline is more than a black box—you can still access and inspect each preprocessing step whenever needed.

Predicting

In [22]:
y_pred = pipe.predict(X_test)
y_pred

array([0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1])

In [23]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.820627802690583

Cross Validation using Pipeline

In [24]:
from sklearn.model_selection import cross_val_score
cross_val_score(pipe, X_train, y_train, cv=5, scoring='accuracy').mean()

np.float64(0.7544495567276399)

GridSearch using Pipeline

In [25]:
# gridsearchcv
params = {
    'decisiontreeclassifier__max_depth': [1, 2, 3, 4, 5, None]
}

from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(pipe, params, cv=5, scoring='accuracy')
grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('columntransformer-1',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('impute_age',
                                                                         SimpleImputer(),
                                                                         [2]),
                                                                        ('impute_embarked',
                                                                         SimpleImputer(strategy='most_frequent'),
                                                                         [6])])),
                                       ('columntransformer-2',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('encode_sex_embarked',
                                                                         OneHotEncoder(handle_un...
                                                                                       sparse_output=False),
                                                                         [1,
                                                                          3])])),
                                       ('columntransformer-3',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('scale',
                                                                         MinMaxScaler(),
                                                                         slice(0, 10, None))])),
                                       ('selectkbest',
                                        SelectKBest(k=8,
                                                    score_func=<function chi2 at 0x79574d8e7e20>)),
                                       ('decisiontreeclassifier',
                                        DecisionTreeClassifier())]),
             param_grid={'decisiontreeclassifier__max_depth': [1, 2, 3, 4, 5,
                                                               None]},
             scoring='accuracy')

In [26]:
grid.best_score_

np.float64(0.8099427673661765)

In [27]:
grid.best_params_

{'decisiontreeclassifier__max_depth': 3}

Exporting

In [28]:
import pickle
pickle.dump(pipe, open("pipe.pkl", "wb"))

Loading and using

In [29]:
loaded_pipe = pickle.load(open("pipe.pkl", "rb"))

In [30]:
test_input = pd.DataFrame({
    "Pclass": [1],
    "Sex": ["female"],
    "Age": [21],
    "SibSp": [1],
    "Parch": [2],
    "Fare": [50],
    "Embarked": ["S"]
})

In [31]:
loaded_pipe.predict(test_input)

array([1])

---

# 🧠 Real-World Workflow

```
Dataset
   │
   ▼
Train-Test Split
   │
   ▼
Pipeline
   ├── Missing Value Imputation
   ├── Encoding
   ├── Feature Scaling
   ├── Feature Selection
   └── Machine Learning Model
   │
   ▼
Predictions
   │
   ▼
Evaluation
```

This is the workflow used in many production ML systems.


---

# 🎉 Conclusion

Scikit-learn Pipelines are one of the most powerful tools for building reliable Machine Learning workflows. They combine preprocessing and model training into a single, reusable object, making your code cleaner, reducing the risk of data leakage, and simplifying evaluation, tuning, and deployment. Mastering pipelines is an essential step toward writing production-ready Machine Learning code.

---

# 🚀 What's Next?

In the next notebook, you'll learn **🤖 ML 21 — ColumnTransformer in Scikit-learn**.

You'll discover how to apply **different preprocessing techniques to different columns**—for example, scaling numerical features while encoding categorical features—all within a single, efficient workflow. This is the standard approach for handling real-world tabular datasets with mixed feature types.