In [17]:
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

import scipy.stats as stats

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

from sklearn.preprocessing import PowerTransformer

In [12]:
df = pd.read_csv("/kaggle/input/datasets/ahmedfakhar123/used-car-price-prediction-dataset/BMW_Cars_Pakistan.csv")
df

,Unnamed: 0,Car Name,Auction Rating,Model Year,Mileage,Fuel Type,Engine Capacity,Transmission,Engine Unit,Price (PKR)
0,0,BMW 7 Series 5th (F01) Generation 2013 ActiveH...,NaN,2013,52000,Hybrid,3000.0,Automatic,cc,NaN
1,1,BMW X5 2012 xDrive50i for Sale,8.0,2012,102148,Petrol,4400.0,Automatic,cc,16000000.0
2,2,BMW 7 Series 2017 740 Le xDrive for Sale,NaN,2017,48000,Hybrid,2000.0,Automatic,cc,34500000.0
3,3,BMW 2 Series 2021 218i Gran Coupe for Sale,9.3,2021,68064,Petrol,1500.0,Manual,cc,13500000.0
4,4,BMW X1 2017 sDrive18i A/T for Sale,8.6,2017,138928,Petrol,1500.0,Automatic,cc,8200000.0
...,...,...,...,...,...,...,...,...,...,...
339,339,BMW X5 2007 xDrive30d for Sale,NaN,2007,103000,Diesel,3000.0,Automatic,cc,8475000.0
340,340,BMW iX3 2022 M Sport for Sale,NaN,2022,13500,Electric,73.0,Automatic,kWh,20000000.0
341,341,BMW 3 Series 2013 for Sale,NaN,2013,70000,Petrol,1600.0,Manual,cc,8000000.0
342,342,BMW M5 2019 for Sale,NaN,2019,59000,Petrol,4400.0,Automatic,cc,45500000.0
343,343,BMW 3 Series 1996 for Sale,NaN,1996,55000,Petrol,3000.0,Manual,cc,1850000.0

In [16]:
df.fillna({"Price (PKR)": df["Price (PKR)"].mean()}, inplace=True)
df

,Unnamed: 0,Car Name,Auction Rating,Model Year,Mileage,Fuel Type,Engine Capacity,Transmission,Engine Unit,Price (PKR)
0,0,BMW 7 Series 5th (F01) Generation 2013 ActiveH...,NaN,2013,52000,Hybrid,3000.0,Automatic,cc,1.987818e+07
1,1,BMW X5 2012 xDrive50i for Sale,8.0,2012,102148,Petrol,4400.0,Automatic,cc,1.600000e+07
2,2,BMW 7 Series 2017 740 Le xDrive for Sale,NaN,2017,48000,Hybrid,2000.0,Automatic,cc,3.450000e+07
3,3,BMW 2 Series 2021 218i Gran Coupe for Sale,9.3,2021,68064,Petrol,1500.0,Manual,cc,1.350000e+07
4,4,BMW X1 2017 sDrive18i A/T for Sale,8.6,2017,138928,Petrol,1500.0,Automatic,cc,8.200000e+06
...,...,...,...,...,...,...,...,...,...,...
339,339,BMW X5 2007 xDrive30d for Sale,NaN,2007,103000,Diesel,3000.0,Automatic,cc,8.475000e+06
340,340,BMW iX3 2022 M Sport for Sale,NaN,2022,13500,Electric,73.0,Automatic,kWh,2.000000e+07
341,341,BMW 3 Series 2013 for Sale,NaN,2013,70000,Petrol,1600.0,Manual,cc,8.000000e+06
342,342,BMW M5 2019 for Sale,NaN,2019,59000,Petrol,4400.0,Automatic,cc,4.550000e+07
343,343,BMW 3 Series 1996 for Sale,NaN,1996,55000,Petrol,3000.0,Manual,cc,1.850000e+06